[human]
name = "steve"
age = 24.0

[human.info]
location = { day = "Eorzea", night = "Sanctuary" }
class = "rogue"
occupation = "devops engineer"
allergies = "**buzzwords**"
interests = ["Rust", "Scala 3", "Kubernetes", "DevOps"]
quote = "functional programming is my destiny, i just don't know how to do it yet"

[human.contact]
email = "stevenkotwal@ufl.edu"
discord = "steve4"
website = "pnada dot co"
